name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest
    env:
      GOOGLE_TAG_ID: ""
      HOST_NAME: ""
      RAILS_PG_EXTRAS_USER: ""
      RAILS_PG_EXTRAS_PASSWORD: ""

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install yarn packages
        run: yarn install --pure-lockfile

      - name: Run Tests
        run: |
          bundle exec rails db:prepare
          bundle exec rails assets:precompile
          bundle exec rails test
        env:
          DATABASE_HOST: localhost

      - name: Run Standardrb
        run: bundle exec standardrb

      - name: Run Brakeman
        run: bundle exec brakeman